# Generated by Django 5.0.6 on 2024-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='id',
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
