# Generated by Django 5.0.6 on 2024-07-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_answer_voter_question_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_cnt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.question')),
            ],
        ),
    ]
